name: Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: build
      run: go build -v

    - name: test
      run: go test --race -v ./...

    - name: vet
      run: go vet ./...

    - name: staticcheck
      run: |
        go install honnef.co/go/tools/cmd/staticcheck@latest
        staticcheck ./...
